[tool.ruff]
include = ["**/*.py"]
exclude = [
    ".git/",
    ".idea/",
    ".mypy_cache/",
    ".ruff_cache/",
    "doc/",
    "env/lang/",
    "out/",
    "cfg/"
]

respect-gitignore = false
line-length = 80
indent-width = 4
target-version = "py312"
unsafe-fixes = true

[tool.ruff.lint]
select = ["F", "E", "W", "UP", "D", "PL", "NPY", "PD", "N", "I"]
ignore = ["D203", "D212", "F401", "E402"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
exclude = [
    "^.git/.*",
    "^.idea/.*",
    "^.mypy_cache/.*",
    "^.ruff_cache/.*",
    "^doc/.*",
    "^env/lang/.*",
    "^out/.*",
    "^cfg/.*"
]

python_version = "3.12"
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    "lang.*",
    "aioconsole.*",
    "pytube.*",
    "yt_dlp.*",
]
ignore_missing_imports = true
